### ISSUE TITLE
#49 Aus allen Geräten ausloggen (Backend)

### ISSUE THREAD

**Issue by Y4nnikH** [BP-WiSe21-22-Gruppe-52/BP-backend#92]
Als User*in möchte ich mich aus allen Geräten ausloggen können, um die Sicherheit meines Accounts zu gewährleisten.

Akzeptanzkriterium: In den Einstellungen gibt es einen Button, über den alle Refresh-Token devalidiert werden können. Dadurch muss sich in allen Browsern erneut angemeldet werden. Im aktuellen Browser bleibt man jedoch eingeloggt

Aufwand: 1 Story Points.

- [ ] Neuen Token senden, damit aktueller Browser eingeloggt bleibt

**Comment by Laennart** [comment]
This is implemented in the frontend already. You can only send the new `refresh_token` and the frontend will request `/api/auth` for a new SessionToken. Best case would be that you would return a new `refresh_token` as well as a `session_token`, which would make the app faster.
